[tool.isort]
profile = "black"
src_paths = ["kivy_garden"]
force_sort_within_sections=true
line_length=80
multi_line_output=3

[tool.black]
line-length=80
target-version=['py37','py38','py39','py310','py311']
